MAKE_DIRS= IOInterface\
    	   dataLump \
    	   StdWriter\
		   binaryDescribe\
		   Utils \
		   csv \
		     \
		      \
		    \
		   commands \
		   regex \
		   strings  \
		   CEF

MODE=CPP


include ../../../makefile.include
