MAKE_DIRS= IOInterface\
    	   dataLump \
    	   StdWriter\
		   binaryDescribe\
		   Utils \
		   csv \
		     \
		      \
		   commands \
		   regex \
		   strings  \
		   JSON \
		   ThreadComms

MODE=CPP


include ../../../makefile.include
