MAKE_DIRS= libIOInterface\
		   libUtils \
		   libString \
		   libJSON \
		   libTest \
		     \
		      \
		   libScreen \
		   libMeta \
		   libCommands \
		   libGTK \
		   libCEF

MODE=CPP

include ../../../makefile.include
